var exercises = [
  // id, title
  { id: "00_tutorial", name: "Tutorial", level: 1 },
  { id: "01_globale_variable", name: "Globale Variablen", level: 1 },
  { id: "02_eingabe_prompt", name: "Eingaben über prompt()", level: 1 },
  { id: "03_ausgabe_alert", name: "Ausgaben über alert()", level: 1 },
  { id: "04_html_el_man_1", name: "HTML Elemente manipulieren 1", level: 1 },
  { id: "05_html_el_man_2", name: "HTML Elemente manipulieren 2", level: 2 },
  { id: "06_html_el_man_3", name: "HTML Elemente manipulieren 3", level: 2 },
  { id: "07_input_field_1", name: "Eingabefeld auslesen 1", level: 1 },
  { id: "08_input_field_2", name: "Eingabefeld auslesen 2", level: 2 },
  { id: "09_datentyp_number", name: "Datentyp Number", level: 1 },
  { id: "10_datentyp_string", name: "Datentyp String", level: 1 },
  { id: "11_datentyp_mix", name: "Verschiedene Datentypen mischen", level: 2 },
  { id: "12_datentyp_bool_vergleich", name: "Datentyp Boolean und Vergleiche", level: 2 },
  { id: "13_bedingungen", name: "Bedingungen", level: 2 },
  { id: "14_bedingte_anweisungen", name: "Bedingte Anweisungen", level: 2 },
  { id: "15_verzweigung_1x1", name: "Verzweigung (1x1)", level: 1 },
  { id: "16_verzweigung", name: "Verzweigungen", level: 2 },
  { id: "17_verzweigung_catchIt", name: "Verzweigungen (CatchIt)", level: 2 },
  { id: "18_verzweigung_bugshoot", name: "Verzweigungen (Bugshooter)", level: 2 },
  { id: "19_while_bedingung", name: "While mit Bedingung", level: 1},
  { id: "20_while_durchschnitt", name: "While (Durchschnitt)", level: 2 },
  { id: "21_array_numbers", name: "Array mit Zahlen", level: 1},
  { id: "22_array_string", name: "Array (Farbstrings)", level: 2 },
  { id: "23_while_mailstring", name:"While mit String als Array", level:3},
  { id: "24_for-counter", name: "for-Schleife Quadratzahlen", level: 1},
  { id: "25_for-groesste", name: "for-Schleife größte Zahl", level: 2},
  { id: "26_funktionen", name: "Funktionen Summenberechnung", level: 1},
  { id: "27_funkt_mitternacht", name: "Funktion Mitternachtsformel", level: 2},
];

export { exercises };